### ISSUE TITLE
Difficulty installing PyZgoubi

### ISSUE THREAD

**Issue by dtabell** [PyZgoubi/PyZgoubi#11]
After executing `./setup.py install` in my PyZgoubi dir, I test by running `pyzgoubi --version`. It emits the error
```python
jupyter> pyzgoubi --version
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/py3/bin/pyzgoubi", line 4, in <module>
    __import__('pkg_resources').run_script('pyzgoubi==0.8.0a1', 'pyzgoubi')
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1436, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/pyzgoubi' not found in metadata at '/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pyzgoubi-0.8.0a1.dist-info'
```

**Comment by Sam-Tygier** [comment]
I am struggling to reproduce this error. Could you give a bit more detail about your set up?

Thanks,
Sam
